# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
      name: Publish docker image to registry
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
      
        - name: Login to Docker.Hub
          uses: docker/login-action@v1.14.1
          with:
            #username and pw for hub acc
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PW }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v3.7.0
          with:
            #credentials for public repository access to docker-hub
            images: ${{ secrets.DOCKER_HUB_NS }}/${{ secrets.DOCKER_HUB_REPO }}
        
        - name: Build and push docker image
          uses: docker/build-push-action@v2.10.0
          with:
            context: .
            file: ./Dockerfile
            #platforms: linux/amd64,linux/arm64
            push: true
            labels: ${{ steps.meta.outputs.labels }}
            tags: ${{ steps.meta.outputs.tags }}
      
          
